name: Scrimsight Code Review
description: Review PRs against Scrimsight coding standards using Gemini
inputs:
  gemini-api-key:
    description: Gemini API key
    required: true
  github-token:
    description: GitHub token
    required: true
  standards:
    description: JSON array of review standards with name/description/examples
    required: true
runs:
  using: node20
  main: dist/main.js 